### ISSUE TITLE
USI Tools meta data 

### ISSUE THREAD

**Issue by Ben-ksp** [BobPalmer/CKAN#24]
Olympic1 informed me I should post about this issue here:

https://github.com/KSP-CKAN/NetKAN/issues/5544

error log included in the original post

I THINK but am not sure the meta data for USI tools is either incomplete or incorrect

while you can install the usi tools with CKAN it is not recognized by the other USI mods and being the correct dependant under CKAN,

confirmed with a fresh KSP 1.3 install,  note when installing with the constellation or alone  manually it works fine,  I think it is just in the meta data either not showing as the correct version for all the other usi mods

**Comment by jaxx050** [comment]
i'm having this same issue as well, ckan seems unable to recognize it when trying to install the rest of the USI suite of mods.

**Comment by Bit-Fiddler** [comment]
Same here.
