### ISSUE TITLE
Are you planning to relicense to the GPL (code) + CC (models)?

### ISSUE THREAD

**Issue by Kerbas-ad-astra** [BobPalmer/CKAN#3]
Per discussion on the KSP forum.

**Comment by BobPalmer** [comment]
Close - GPL for code/configs, keeping the models/textures ARR for the moment (other than Karbonite and CRP, which stick with CC for the whole mod).

**Comment by Kerbas-ad-astra** [comment]
Glad to see this revision made in the latest releases.  Thanks!
